# Generated by Django 3.1.3 on 2020-12-02 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Symptom',
            new_name='Symp',
        ),
    ]
